const flagsCollection = [
  { _id: "1", country: "Indianapolis", flagPicture: "indianapolis.png" },
  { _id: "2", country: "70ème Anniversaire", flagPicture: "fia70.png" },
  { _id: "3", country: "Abou Dhabi", flagPicture: "aboudhabi.png" },
  { _id: "4", country: "Argentine", flagPicture: "argentine.png" },
  { _id: "5", country: "Australie", flagPicture: "australie.png" },
  { _id: "6", country: "Autriche", flagPicture: "autriche.png" },
  { _id: "7", country: "Azerbaïdjan", flagPicture: "azerbaidjan.png" },
  { _id: "8", country: "Belgique", flagPicture: "belgique.png" },
  { _id: "9", country: "Bahreïn", flagPicture: "bahreïn.png" },
  { _id: "10", country: "Brésil", flagPicture: "bresil.png" },
  { _id: "11", country: "Canada", flagPicture: "canada.png" },
  { _id: "12", country: "Suisse", flagPicture: "suisse.png" },
  { _id: "13", country: "Chine", flagPicture: "chine.png" },
  { _id: "14", country: "Allemagne", flagPicture: "allemagne.png" },
  { _id: "15", country: "Eifel", flagPicture: "eifel.png" },
  { _id: "16", country: "Emilie-Romagne", flagPicture: "emilie-romagne.png" },
  { _id: "17", country: "Espagne", flagPicture: "espagne.png" },
  { _id: "18", country: "Europe", flagPicture: "europe.png" },
  { _id: "19", country: "France", flagPicture: "france.png" },
  { _id: "20", country: "Grande-Bretagne", flagPicture: "grandebretagne.png" },
  { _id: "21", country: "Hongrie", flagPicture: "hongrie.png" },
  { _id: "22", country: "Inde", flagPicture: "inde.png" },
  { _id: "23", country: "Italie", flagPicture: "italie.png" },
  { _id: "24", country: "Japon", flagPicture: "japon.png" },
  { _id: "25", country: "Corée du Sud", flagPicture: "coree.png" },
  { _id: "26", country: "Luxembourg", flagPicture: "luxembourg.png" },
  { _id: "27", country: "Maroc", flagPicture: "maroc.png" },
  { _id: "28", country: "Monaco", flagPicture: "monaco.png" },
  { _id: "29", country: "Mexique", flagPicture: "mexique.png" },
  { _id: "30", country: "Malaisie", flagPicture: "malaisie.png" },
  { _id: "31", country: "Pays-Bas", flagPicture: "pays_bas.png" },
  { _id: "32", country: "Pacific", flagPicture: "pacific.png" },
  { _id: "33", country: "Pescara", flagPicture: "pescara.png" },
  { _id: "34", country: "Portugal", flagPicture: "portugal.png" },
  { _id: "35", country: "Russie", flagPicture: "russie.png" },
  { _id: "36", country: "Sakhir", flagPicture: "bahreïn.png" },
  { _id: "37", country: "Singapour", flagPicture: "singapour.png" },
  { _id: "38", country: "San Marino", flagPicture: "san_marino.png" },
  { _id: "39", country: "Styrie", flagPicture: "styrie.png" },
  { _id: "40", country: "Suède", flagPicture: "suede.png" },
  { _id: "41", country: "Toscane", flagPicture: "toscane.png" },
  { _id: "42", country: "Turquie", flagPicture: "turquie.png" },
  { _id: "43", country: "Etats-Unis", flagPicture: "usa.png" },
  { _id: "44", country: "Etats-Unis Est", flagPicture: "usa.png" },
  { _id: "45", country: "Etats-Unis Ouest", flagPicture: "usa.png" },
  { _id: "46", country: "Las Vegas", flagPicture: "lasvegas.png" },
  { _id: "47", country: "Vietnam", flagPicture: "vietnam.png" },
  { _id: "48", country: "Afrique du sud", flagPicture: "south_africa.png" },
  { _id: "49", country: "Chili", flagPicture: "chili.png" },
  { _id: "50", country: "Colombie", flagPicture: "colombie.png" },
  { _id: "51", country: "Danemark", flagPicture: "danemark.png" },
  { _id: "52", country: "Ecosse", flagPicture: "ecosse.png" },
  { _id: "53", country: "Finlande", flagPicture: "finlande.png" },
  { _id: "54", country: "Pays de Galles", flagPicture: "galles.png" },
  { _id: "55", country: "Indonésie", flagPicture: "indonesie.png" },
  { _id: "56", country: "Irlande", flagPicture: "irlande.png" },
  { _id: "57", country: "Israël", flagPicture: "israel.png" },
  { _id: "58", country: "Liechtenstein", flagPicture: "liechtenstein.png" },
  { _id: "59", country: "Nouvelle Zélande", flagPicture: "new_zealand.png" },
  { _id: "60", country: "Pologne", flagPicture: "pologne.png" },
  { _id: "61", country: "Rhodésie", flagPicture: "rhodesie.png" },
  { _id: "62", country: "Tchequi", flagPicture: "tchequi.png" },
  { _id: "63", country: "Thaïlande", flagPicture: "thailande.png" },
  { _id: "64", country: "Uruguay", flagPicture: "uruguay.png" },
  { _id: "65", country: "Venezuela", flagPicture: "venezuela.png" },
  { _id: "66", country: "Mexico", flagPicture: "mexico.png" },
  { _id: "67", country: "São Paulo", flagPicture: "saopaulo.png" },
  { _id: "68", country: "Arabie Saoudite", flagPicture: "arabie.png" },
  { _id: "69", country: "Qatar", flagPicture: "qatar.png" },
];

export default flagsCollection;
