const teamCollection = [
  { team: "Ferrari", logo: "ferrari.png" },
  { team: "McLaren", logo: "mclaren.png" },
  { team: "Williams", logo: "williams.png" },
  { team: "Mercedes", logo: "mercedes.png" },
  { team: "Alfa Romeo", logo: "alfaromeo.png" },
  { team: "Red Bull", logo: "redbull.png" },
  { team: "AlphaTauri", logo: "alphatauri.png" },
  { team: "Haas", logo: "haas.png" },
  { team: "Aston Martin", logo: "astonmartin.png" },
  { team: "Alpine", logo: "alpine.png" },
  { team: "Lotus", logo: "lotus.png" },
  { team: "Renault", logo: "renault.png" },
  { team: "Brabham", logo: "brabham.png" },
  { team: "Benetton", logo: "benetton.png" },
  { team: "Tyrrell", logo: "tyrrell.png" },
  { team: "Cooper", logo: "cooper.png" },
  { team: "BRM", logo: "brm.png" },
  { team: "Maserati", logo: "maserati.png" },
  { team: "Ligier", logo: "ligier.png" },
  { team: "Vanwall", logo: "vanwall.png" },
  { team: "March", logo: "march.png" },
  { team: "Brawn GP", logo: "brawngp.png" },
  { team: "Matra", logo: "matra.png" },
  { team: "Shadow", logo: "shadow.png" },
  { team: "Toyota", logo: "toyota.png" },
  { team: "Lancia", logo: "lancia.png" },
  { team: "Honda", logo: "honda.png" },
  { team: "Jordan", logo: "jordan.png" },
  { team: "BAR", logo: "bar.png" },
  { team: "Lola", logo: "lola.png" },
  { team: "Porsche", logo: "porsche.png" },
  { team: "Wolf", logo: "wolf.png" },
  { team: "Arrows", logo: "arrows.png" },
  { team: "Toleman", logo: "toleman.png" },
  { team: "Stewart Grand Prix", logo: "stewartgp.png" },
  { team: "BMW Sauber", logo: "bmwsauber.png" },
  { team: "Toro Rosso", logo: "tororosso.png" },
  { team: "Force India", logo: "forceindia.png" },
  { team: "Racing Point", logo: "racingpoint.png" },
  { team: "Eagle", logo: "eagle.png" },
  { team: "Hesketh", logo: "hesketh.png" },
  { team: "Penske", logo: "penske.png" },
  { team: "Surtees", logo: "surtees.png" },
  { team: "Gordini", logo: "gordini.png" },
  { team: "Parnelli", logo: "parnelli.png" },
  { team: "Ensign", logo: "ensign.png" },
  { team: "Sauber", logo: "sauber.png" },
  { team: "Talbot Lago", logo: "talbot.png" },
  { team: "Fittipaldi", logo: "fittipaldi.png" },
  { team: "Dallara", logo: "dallara.png" },
  { team: "Prost Grand Prix", logo: "prostgp.png" },
  { team: "Connaught", logo: "connaught.png" },
  { team: "Copersucar", logo: "copersucar.png" },
  { team: "Onyx", logo: "onyx.png" },
  { team: "Leyton House", logo: "leytonhouse.png" },
  { team: "Footwork", logo: "footwork.png" },
  { team: "Jaguar", logo: "jaguar.png" },
  { team: "AGS", logo: "ags.png" },
  { team: "Amon", logo: "amon.png" },
  { team: "Andrea Moda", logo: "andreamoda.png" },
  { team: "ATS", logo: "ats.png" },
  { team: "Boro", logo: "boro.png" },
  { team: "Bugatti", logo: "bugatti.png" },
  { team: "Caterham", logo: "caterham.png" },
  { team: "Connew", logo: "connew.png" },
  { team: "De Tomaso", logo: "detomaso.png" },
  { team: "Eifelland", logo: "eifelland.png" },
  { team: "Eurobrun", logo: "eurobrun.png" },
  { team: "Forti", logo: "forti.png" },
  { team: "Hill", logo: "embassy_hill.png" },
  { team: "HRT", logo: "hrt.png" },
  { team: "Iso", logo: "iso.png" },
  { team: "Lamborghini", logo: "lamborghini.png" },
  { team: "Larrousse", logo: "larrousse.png" },
  { team: "LDS", logo: "lds.png" },
  { team: "Virgin", logo: "virgin.png" },
  { team: "Marussia", logo: "marussia.png" },
  { team: "Manor", logo: "manor.png" },
  { team: "Martini", logo: "martini.png" },
  { team: "Merzario", logo: "merzario.png" },
  { team: "Midland", logo: "midland.png" },
  { team: "Minardi", logo: "minardi.png" },
  { team: "Osella", logo: "osella.png" },
  { team: "Pacific", logo: "pacific.png" },
  { team: "Rial", logo: "rial.png" },
  { team: "Simtek", logo: "simtek.png" },
  { team: "Spyker", logo: "spyker.png" },
  { team: "Super Aguri", logo: "superaguri.png" },
  { team: "Theodore", logo: "theodore.png" },
  { team: "Zakspeed", logo: "zakspeed.png" },
  { team: "Venturi", logo: "venturi.png" },
  { team: "Fondmetal", logo: "fondmetal.png" },
];

export default teamCollection;
